Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AuthEg.Models;

namespace AuthEg.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private OrganizationDBEntities db = new OrganizationDBEntities();

        // GET: Department
        [Authorize(Roles ="V, A")]
        public ActionResult Index()
        {
            return View(db.tbl_Dept.ToList());
        }

        // GET: Department/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Dept tbl_Dept = db.tbl_Dept.Find(id);
            if (tbl_Dept == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Dept);
        }

        // GET: Department/Create
        [Authorize(Roles = "A")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Department/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DId,DName,HOD")] tbl_Dept tbl_Dept)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Dept.Add(tbl_Dept);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Dept);
        }

        // GET: Department/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Dept tbl_Dept = db.tbl_Dept.Find(id);
            if (tbl_Dept == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Dept);
        }

        // POST: Department/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DId,DName,HOD")] tbl_Dept tbl_Dept)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Dept).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Dept);
        }

        // GET: Department/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Dept tbl_Dept = db.tbl_Dept.Find(id);
            if (tbl_Dept == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Dept);
        }

        // POST: Department/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Dept tbl_Dept = db.tbl_Dept.Find(id);
            db.tbl_Dept.Remove(tbl_Dept);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AuthEg.Models;

namespace AuthEg.Controllers
{
    public class EmployeeController : Controller
    {
        private OrganizationDBEntities db = new OrganizationDBEntities();

        // GET: Employee
        [Authorize(Roles = "V, A")]
        public ActionResult Index()
        {
            var tbl_Emp = db.tbl_Emp.Include(t => t.tbl_Dept);
            return View(tbl_Emp.ToList());
        }

        // GET: Employee/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Emp tbl_Emp = db.tbl_Emp.Find(id);
            if (tbl_Emp == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Emp);
        }

        // GET: Employee/Create
        [Authorize(Roles = "A")]
        public ActionResult Create()
        {
            ViewBag.DeptId = new SelectList(db.tbl_Dept, "DId", "DName");
            return View();
        }

        // POST: Employee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EId,Ename,Salary,DOB,DeptId")] tbl_Emp tbl_Emp)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Emp.Add(tbl_Emp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DeptId = new SelectList(db.tbl_Dept, "DId", "DName", tbl_Emp.DeptId);
            return View(tbl_Emp);
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Emp tbl_Emp = db.tbl_Emp.Find(id);
            if (tbl_Emp == null)
            {
                return HttpNotFound();
            }
            ViewBag.DeptId = new SelectList(db.tbl_Dept, "DId", "DName", tbl_Emp.DeptId);
            return View(tbl_Emp);
        }

        // POST: Employee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EId,Ename,Salary,DOB,DeptId")] tbl_Emp tbl_Emp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Emp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DeptId = new SelectList(db.tbl_Dept, "DId", "DName", tbl_Emp.DeptId);
            return View(tbl_Emp);
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Emp tbl_Emp = db.tbl_Emp.Find(id);
            if (tbl_Emp == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Emp);
        }

        // POST: Employee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Emp tbl_Emp = db.tbl_Emp.Find(id);
            db.tbl_Emp.Remove(tbl_Emp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("ViewDept", "Index", "Department")</li>
                        <li>@Html.ActionLink("ViewEmp", "Index", "Employee")</li>
                        if (User.IsInRole("A"))
                        {
                            <li>@Html.ActionLink("CreateDept", "Create", "Department")</li>
                            <li>@Html.ActionLink("CreateEmp", "Create", "Employee")</li>
                        }
                        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                        <li><a href="#">Welcome Mr/Ms: @User.Identity.Name</a></li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                    }
                </ul>

            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>